name: Rodar Robo de Escanteios

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  rodar-script:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o codigo do Github
        uses: actions/checkout@v3

      - name: Configurar o Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar as bibliotecas
        run: pip install -r requisitos.txt

      - name: Executar o Robo
        run: python main.py
        
